http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  web:
    host: localhost
    paths: '*'
  server:
    host: localhost
    paths: '/server/*'
serviceEndpoints:
  web:
    url: 'http://localhost:4200'
  server:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  webPipeline:
    apiEndpoints:
      - web
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: web 
              changeOrigin: true
  serverPipeline:
    apiEndpoints:
      - server
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: server 
              changeOrigin: true
              stripPath: true
